language: python

python:
  - {% if cookiecutter.cli_type == 'toil' %}2.7{% else %}3.6{% endif %}

services:
  - docker

install:
  - pip install -U codecov

script:
  - bash test-container.sh

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {% if cookiecutter.github_account == 'leukgen' %}leukgen{% else %}<REPLACE>{% endif %}
  password: <TO REPLACE THIS RUN `travis encrypt --add deploy.password`>
  on:
    tags: true
    repo: {{cookiecutter.github_account}}/{{cookiecutter.project_slug}}
    python: {% if cookiecutter.cli_type == 'toil' %}2.7{% else %}3.6{% endif %}
    branch: master
