language: python

python:
  - 3.9

services:
  - docker

install:
  - pip install -U codecov

script:
  - bash test-container.sh

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: {% if cookiecutter.github_account == 'papaemmelab' %}papaemmelab{% else %}<REPLACE>{% endif %}
  password: <TO REPLACE THIS RUN `travis encrypt --add deploy.password`>
  on:
    tags: true
    repo: {{cookiecutter.github_account}}/{{cookiecutter.project_slug}}
    python: 3.9
    branch: master
